### ISSUE TITLE
Wrong cardinalities 0..* for relators

### ISSUE THREAD

**Issue by MichalMed** [datagov-cz/ontoGrapher#276] opened 2021-05-21 10:02 UTC
Relator must have at least one object on each side (má vztažený prvek 1/2), but the default cardinality for domain and range of relators is 0..*

**Comment by bindeali** [comment] 2023-12-21 15:47
Closing as the default cardinality can now be set manually and also because this is a duplicate of #369 .

**Closed by bindeali** 2023-12-21 15:47 UTC
